AllCops:
    NewCops: enable
Layout/EmptyLinesAroundModuleBody:
    Enabled: false
Layout/EmptyLinesAroundClassBody:
    Enabled: false
Layout/IndentationWidth:
    Width: 4
Layout/LineLength:
    Enabled: false
